### ISSUE TITLE
Add cross-browser support

### ISSUE THREAD

**Issue by kichinsky** [kichinsky/CanvasTools-for-VOTT#22]
The current implementation does not work in Edge due to some SVG-related API (e.g. masks).

**Comment by soyfestivo** [comment]
Is there any plan to make this more compatible with Edge?

**Comment by kichinsky** [comment]
Yeah, there two sides:
- Short-term. I need to check but seems like I can update rect-selection experience to exclude using masks from SVG, it should make the tool compatible with Edge. At least I don't remember other critical issues, but still, I need to manually check.
- Middle-to-long term. My current plan is to work on compatibility after setting up some automated testing environment and covering the source code with enough tests.

**Comment by kichinsky** [comment]
@soyfestivo I think, I fixed all major issues in just released beta https://www.npmjs.com/package/vott-ct/v/2.2.0-beta.0. Let me know if you find something new.
