### ISSUE TITLE
Draw the annotations differently dependent on their type

### ISSUE THREAD

**Issue by Legor** [kichinsky/CanvasTools-for-VOTT#34]
You probably have that on your sheet allready but I wanted to add this for completeness.
As for now there are 4 different kind of annotations (rect, template, point, polygon) however as they are drawn on the image they all look very much alike.

I think the following ideas are related to this
- Draw a point as a point (not as a small rectangle), also a point annotation should not be resizable
- Draw the single nodes of a polygon, not only the bounding box

Greetings!

**Comment by kichinsky** [comment]
Done in v2.1.0. Should be added to VoTT 1.x soon.
