### ISSUE TITLE
Toolbar icons not displaying

### ISSUE THREAD

**Issue by soyfestivo** [kichinsky/CanvasTools-for-VOTT#45]
Toolbar icons are not displaying in the demos or when included via the `vott-ct` npm package.
![image](https://user-images.githubusercontent.com/1487328/54059621-a59aa080-41ae-11e9-9e8f-0f0001e944c2.png)

**Comment by kichinsky** [comment]
Yeah, it is something around the relative path to icons. Does it work if you run samples from the localhost?

**Comment by soyfestivo** [comment]
No, running samples with localhost I still get this problem

**Comment by kichinsky** [comment]
Ok, can you open browser devtools and check what are the error messages?

**Comment by soyfestivo** [comment]
As it turns out running the samples locally is caused by CORS. After playing with the relative path and making sure the assets were included I managed to get it working. We can close this request.
