### ISSUE TITLE
Adding a clear button to the toolbar

### ISSUE THREAD

**Issue by soyfestivo** [kichinsky/CanvasTools-for-VOTT#46]
It would be nice if there could be a button on the toolbar for clearing all current regions from the canvas. In playing with the tool it is easy to make accidental mistakes that are hard to remove (making a very small rectangular selection).

Can you add a button that clears the regions?

**Comment by kichinsky** [comment]
Added in #50

**Comment by soyfestivo** [comment]
Thank you! 😃
