### ISSUE TITLE
Add UI-element to track background toggling 

### ISSUE THREAD

**Issue by kichinsky** [kichinsky/CanvasTools-for-VOTT#47]
Currently, it is not clear from UI what is the current status of the region background toggling. => Add a switch-button to the toolbar.

Related to: https://github.com/Microsoft/VoTT/issues/663

**Comment by amitportish** [comment]
Hi Kichinsky
Did you add the feature to the head branch of the canvasTools?
How do I utilize it?

**Comment by kichinsky** [comment]
It is not implemented yet, I'm projecting to make the required changes in few days.

**Comment by kichinsky** [comment]
@amitportish Could you check the samples for CanvasTools or the screenshot bellow if it fits your request?

![image](https://user-images.githubusercontent.com/979457/54597482-b4534400-4a47-11e9-8497-48bed4596af4.png)

p.s. It is not integrated into VoTT yet. It will take another day or so for the 1.x version.

**Comment by amitportish** [comment]
Thank you, It's good.
I would install the new CanvasTool.
Would it work with ctrl B?
