### ISSUE TITLE
vott-ct v2.1.25 compile bug

### ISSUE THREAD

**Issue by soyfestivo** [kichinsky/CanvasTools-for-VOTT#52]
There is an issue with the current version I cannot get it to compile right when imported into another project: `Module not found: Can't resolve '../../Core/Point2D' in '.\node_modules\vott-ct\lib\js\CanvasTools\Region\Component'`:

![image](https://user-images.githubusercontent.com/1487328/54240468-5bc9f700-44db-11e9-9954-eb390d51bff4.png)

**Comment by kichinsky** [comment]
Yeah, it seems like the package is somehow corrupted, not sure why. Can you check the node modules folder, if it contains the `vott-ct\lib\js\CanvasTools\Core` folder?

**Comment by kichinsky** [comment]
Should be fixed in 2.1.27
